version: '3.8'

services:
  app:
    build: .
    container_name: spring-boot-app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=$USERNAME
      - POSTGRES_PASSWORD=$PASSWORD
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/$DB_NAME
      - SPRING_DATASOURCE_USERNAME=$USERNAME
      - SPRING_DATASOURCE_PASSWORD=$PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=$USERNAME
      - POSTGRES_PASSWORD=$PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - "$LOCAL_PORT:$DOCKER_PORT"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
